version: 2

multi-ecosystem-groups:
  bun-updates:
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
  actions-updates:
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore"
    labels:
      - "dependencies"
  nix-updates:
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore"
    labels:
      - "dependencies"

updates:
  - package-ecosystem: "bun"
    directories:
      - "/"
      - "apps/*"
    patterns:
      - "*"
    multi-ecosystem-group: "bun-updates"
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    directory: "/"
    patterns:
      - "*"
    multi-ecosystem-group: "actions-updates"
    schedule:
      interval: "daily"

  - package-ecosystem: "nix"
    directory: "/"
    patterns:
      - "*"
    multi-ecosystem-group: "nix-updates"
    schedule:
      interval: "daily"
