telemetry = false
logLevel = "warn"

[install]
exact = false
auto = "auto"

linker = "isolated"

minimumReleaseAge = 129600
peer = false


[install.cache]
disable = false
disableManifest = false

[console]
depth = 3

[test]
coverage = true
coverageReporter = ["text", "lcov"]
retry = 2
randomize = true
onlyFailures = true

[run]
bun = false
silent = true
