# .github/workflows/_setup.yml
on:
  workflow_call:
    inputs:
      run-command:
        required: false
        type: string

jobs:
  run:
    runs-on: ubuntu-latest
    environment: development
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v6
      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: actions/cache@v5
        with:
          path: |
            /nix/store
            ~/.nix-profile
          key: ${{ runner.os }}-nix-store-${{ hashFiles('flake.lock') }}
          restore-keys: |
            ${{ runner.os }}-nix-store-

      - run: nix develop -c bun install --frozen-lockfile

      - run: nix develop -c bun run cf-typegen

      - run: nix develop -c ${{ inputs.run-command }}
        if: inputs.run-command != ''
