name: CI

permissions:
  contents: read
  id-token: write

on:
  pull_request:
    types:
      - opened
      - synchronize

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  format:
    uses: ./.github/workflows/_setup.yml
    with:
      run-command: bun run format

  lint:
    uses: ./.github/workflows/_setup.yml
    with:
      run-command: bun run lint

  knip:
    uses: ./.github/workflows/_setup.yml
    with:
      run-command: bunx knip

  type-check:
    uses: ./.github/workflows/_setup.yml
    with:
      run-command: bun run type-check

  build:
    uses: ./.github/workflows/_setup.yml
    with:
      run-command: bun run build-only

  test:
    uses: ./.github/workflows/_setup.yml
    with:
      run-command: bun run test
