name: Weekly Update and PR

on:
  schedule:
    - cron: '0 0 * * 1'

jobs:
  update-and-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Update packages
        run: bun update -r
      - name: Commit changes
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions-[bot]"
          git add .
          git commit -m "Weekly update: $(date +'%Y-%m-%d')"
      - name: Push to new branch
        run: git push origin update-weekly
      - name: Create pull request
        run: gh pr create --title "Weekly update PR" --body "Automated weekly update PR" --base main --head update-weekly
